appenders:
  file:
    kind: file
    path: log/current.log
    append: false
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.6f)} # {l}: {M}:{L} :: {m}{n}"
root:
  level: trace
  appenders:
    - file